@startuml
title Bridge ZEC.z to ZEC Communication F\nBridging Failed
top to bottom direction

class "ZavaX\nAgent" as ZA
class "ZavaX\nConsensus\nEngine" as ZCE
class "ZEC.z\nContract" as ZC
class "Avalanche\nC-Chain" as CC

ZCE -up-> ZA : **40: Message to refund ZEC.z from escrow**
ZA -up-> ZC : 41: Message + gas
ZC -down-> ZC : 42: Verify warp signature\n& weight
ZC -down-> CC : 43: Refund ZEC.z
CC -up-> ZC : 44: Confirmation

@enduml