@startuml
title Bridge ZEC.z to ZEC Communication B
top to bottom direction

class "ZEC Owner" as ZO
class "ZavaX\nBridge UI" as UI
class "Core\nWallet" as MC
class "ZEC.z\nContract" as ZC
class "ZavaX\nAgent" as ZA
class "Avalanche\nC-Chain" as CC

ZO -down-> UI : **11: Initiate bridge reqest**
UI -down-> MC : 12: Sign request
MC -up-> UI : 13: Signed request
UI -down-> ZC : 14: Send bridge request + gas
UI -down-> ZA : 15: Notify: incoming warp message +\ngas for burn/refund
ZC -down-> CC : 16: Verify funds availability
CC -up-> ZC : 17: Funds available

@enduml