@startuml
title Bridge ZEC to ZEC.z Communication A
top to bottom direction

class "ZEC Owner" as ZO
class "ZavaX\nBridge UI" as UI
class "Core\nWallet" as MC
class "Avalanche\nC-Chain" as CC
class "ZavaX\nAgent" as ZA
class "Zebra\n" as Z

ZO -down-> UI : **1: Go to bridge website and **\n**Connect AVAX wallet**
UI -down-> MC : 2: Request ZEC.z balance
MC -down-> CC : 3: Request ZEC.z balance
CC -up-> MC : 4: ZEC.z balance
MC -up-> UI : 5: ZEC.z balance
UI -down-> ZA : 6: Request ZEC balance
ZA -down-> Z : 7: Request ZEC balance
Z -up-> ZA : 8: ZEC balance
ZA -up-> UI : 9: ZEC balance
UI -up-> ZO : 10: Show ZEC.z and ZEC balances & \nZEC transparent address\nassociated with AVAX address

@enduml