@startuml "Maintain ZavaX Wardens Communication A"
top to bottom direction

class "ZEC Owner" as ZH
class "ZavaX\nBridge UI" as UI
class "Core\nWallet" as MC
class "ZavaX\nAgent" as ZA 
class "Zebra\n" as Z
class "Avalanche\nC-Chain" as CC 


ZH -down-> UI : **1: Go to bridge website and**\n**Connect AVAX wallet**
UI -down-> MC : 2: Request ZEC.z balance
MC -down-> CC : 3: Request ZEC.z balance
CC -up-> MC : 4: ZEC.z available balance
MC -up-> UI : 5: ZEC.z available balance
UI -down-> ZA : 6: Request ZEC balance
ZA -down-> Z : 7: Request ZEC balance
Z -up-> ZA : 8: ZEC available balance
ZA -up-> UI : 9: ZEC available balance

@enduml