@startuml
title Bridge ZEC to ZEC.z Communication B
top to bottom direction

class "ZavaX\nBridge UI" as UI
class "ZEC Owner" as ZH
class "Nighthawk/\nYWallet" as YW
class "ZavaX\nAgent" as ZA 
class "Zebra\n" as Z

UI -down-> ZH : **10: Show ZEC.z balance,**\n**ZEC transparent address**\n**associated with AVAX address,**\n**& ZEC balance (initially 0)**
ZH -down-> YW : 11: Send ZEC to transparent address
YW -up-> ZH : 12: Shows transfer complete
UI -down-> ZA : 13: Request ZEC balance update
ZA -down-> Z : 14: Get ZEC available balance
Z -up-> ZA : 15: Updated ZEC available balance
ZA -up-> UI : 16: Updated ZEC available balance
UI -up-> ZH : 17: Shows ZEC available for bridging

@enduml