@startuml
title Bridge ZEC to ZEC.z Communication F
top to bottom direction

class "ZavaX\nBridge UI" as UI
class "Core\nWallet" as MC
class "Avalanche\nC-Chain" as CC
class "ZavaX\nAgent" as ZA
class "Zebra\n" as Z
class "ZEC Owner" as ZH

UI -down-> MC : **38: Request ZEC.z balance**
MC -down-> CC : 39: Request ZEC.z balance
CC -up-> MC : 40: ZEC.z available balance
MC -up-> UI : 41: ZEC.z available balance
ZA -down-> Z : 42: Get ZEC balance
Z -up-> ZA : 43: Updated ZEC balance
ZA -up-> UI : 44: Updated ZEC balance & Results
UI -up-> ZH : 45: Final Results

@enduml