@startuml
title Bridge ZEC to ZEC.z Communication E
top to bottom direction

class "ZavaX\nAgent" as ZA 
class "ZavaX\nConsensus\nEngine" as ZCE
class "ZEC.z\nContract" as ZC
class "Avalanche\nC-Chain" as CC 
class "ZavaX\nBridge UI" as UI

ZA -down-> ZCE : **31: Loop: Poll for warp message**
ZCE -up-> ZA : If approved, continue:\n32: Warp message to mint ZEC.z
ZA -down-> ZC : 33: Relay ZEC.z minting message + gas
ZC -down-> ZC #brown : <color:brown>34: Verify threshold\n<color:brown>signature, weight,\n<color:brown>and not replayed
ZC -down-> ZC #blue : <color:blue>35: Mint ZEC.z
ZC -down-> CC : 36: Send ZEC.z to AVAX wallet address
ZA -up-> UI : 37: Bridging is complete

@enduml