@startuml
title Bridge ZEC.z to ZEC Communication E\nBridging Successful
top to bottom direction

class "ZavaX\nAgent" as ZA
class "ZavaX\nConsensus\nEngine" as ZCE
class "ZEC.z\nContract" as ZC
class "Avalanche\nC-Chain" as CC

ZCE -up-> ZA : **35: Message that ZEC.z can be burnt**
ZA -up-> ZC : 36: Message + gas
ZC -down-> ZC : 37: Verify warp signature\n& weight
ZC -down-> CC : 38: Burn ZEC.z
CC -up-> ZC : 39: Confirmation

@enduml