@startuml
title Bridge ZEC to ZEC.z Communication C
top to bottom direction

class "ZEC Owner" as ZH
class "ZavaX\nBridge UI" as UI
class "Core\nWallet" as MC
class "ZavaX\nAgent" as ZA 
class "Zebra\n" as Z

ZH -down-> UI : **18: Initiate bridge request**
UI -down-> MC : 19: Request signature
MC -up-> UI : 20: Signature
UI -down-> UI : 21: Compose signed ZEC transaction
UI -down-> ZA : 22: Submit signed ZEC transaction + tx fee auth
ZA -down-> Z : 23: Submit signed ZEC transaction

ZA -down-> Z : 24: Poll
Z -up-> ZA : 25: Reply

@enduml