@startuml
left to right direction
title Maintain ZavaX Wardens Communication D

class "ZavaX\nAgent" as ZA
class "Zebra" as Z

ZA -down-> ZA : **23, 24: Combine signatures,**\n**sign xfer**
ZA -down-> Z : 25: Submit signed xfer to new wallet
ZA -down-> Z : 26: Poll for block depth
Z -down-> ZA : 27: Return depth

@enduml