@startuml
skinparam componentStyle uml2
title ZavaX Bridge Components

package "ZavaX Bridge" as ZB {
    [ZavaX\nBridge UI] as UI
    [ZavaX\nAgent] as ZA 
    note top of ZA : ZavaX Agent Tasks:\n• Deliver warp messages\n• Get ZEC balances\n• Submit signed ZEC transactions\n• Initiate warden maintenance\n• Request consensus validation
    [ZavaX\nConsensus\nEngine] as ZCE
    [ZEC.z\nContract] as ZC
}


package "Zebra" as ZCA {
    entity "Zcash Chain" as Z
}

package "AvalancheGo" as A {
    entity "C-Chain" as CC
    entity "P-Chain" as AP
}

UI .d.> ZA : Submit\nbalance reqests &\nbridging messages
UI .d.> CC : Obtain\nbalances\nthrough\nCore\nWallet

ZA .d.> AP : Monitor\nvalidators
ZA .d.> ZCE : Submit bridging &\nwarden maintenance\nmessages
ZA .d.> Z : Submit\nbalance requests &\nbridge transactions
ZA <.d.> ZC : Deliver\ninbound/outbound\nbridging\nmessages

ZCE .d.> Z : Use as\nan oracle
ZCE .d.> AP : Send fee\npayouts &\nwarden\nmaintenance

ZC .d.> CC : Read\n& append

@enduml
 