@startuml

title ZavaX Zcash-Avalanche Bridge

package "ZavaX Bridge" {

    usecase "Maintain Wardens" as UC4
    usecase "Create Validator" as UC3
    usecase "Bridge ZEC.z to ZEC" as UC2
    usecase "Bridge ZEC to ZEC.z" as UC1

    actor "Certified ZavaX Agent" as A4
    actor "ZAX Owner" as A3
    actor "ZEC.z Owner" as A2
    actor "ZEC Owner" as A1

    A4 --> UC4 : Executes
    A3 --> UC3 : Executes
    A2 --> UC2 : Executes
    A1 --> UC1 : Executes
    UC4 --> UC3 : <<include>>

    note bottom of UC4
        Any certified ZavaX Agent (see Terms
        to Know section in the top README.md)
        triggers the ZavaX Consensus Engine
        to include new validators as wardens,
        remove expiring validators as wardens
        (>72 hrs prior to expiry),
        and migrate bridge funds to a wallet
        that is controlled by the new wardens.
    end note

    note bottom of UC4
        The ZavaX consensus engine will only run
        these operations once every 24 hours.
    end note

    note bottom of UC3
        The ZAX holder stakes 2000 ZAX
        to create and operate a
        Validator on the ZavaX
        subnet to run the bridge.
        Within 24 hours it will become
        a warden. Staking is for 30-365 days.
    end note

    note bottom of UC2
        The Avalanche user sends
        ZEC.z and receives ZEC
        on the Zcash blockchain.
    end note

    note bottom of UC1
        The Zcash user sends ZEC
        and receives ZEC.z on
        the Avalanche blockchain.
    end note

}

@enduml
