@startuml

title Bridge ZEC to ZEC.z Sequence

actor "ZEC Owner" as ZH
entity "Nighthawk/\nYWallet" as YW
participant "ZavaX\nBridge UI" as UI
entity "Core\nWallet" as MC
participant "ZavaX\nAgent" as ZA 
entity "Zebra\n" as Z
participant "ZavaX\nConsensus\nEngine" as ZCE
participant "ZEC.z\nContract" as ZC
entity "Avalanche\nC-Chain" as CC 

autonumber
group Gather balance and account info for the ZEC Owner
    ZH -> UI ++: Go to bridge website and \nConnect AVAX wallet
    UI -> MC ++: Request ZEC.z balance
    MC -> CC ++: Request ZEC.z balance
    CC --> MC --: ZEC.z available balance
    MC --> UI --: ZEC.z available balance
    UI -> ZA ++: Request ZEC balance
    ZA -> Z ++: Request ZEC balance
    Z --> ZA : ZEC available balance
    ZA --> UI : ZEC available balance
end

group Initiate bridging from Zcash (wrap ZEC)
    UI --> ZH : Show ZEC.z balance,\nZEC transparent address\nassociated with AVAX address,\n& ZEC balance (initially 0)
    ZH -> YW ++: Send ZEC to transparent address
    YW --> ZH --: Shows transfer complete
    UI -> ZA : Request ZEC balance update
    ZA -> Z : Get ZEC available balance
    Z --> ZA : Updated ZEC available balance
    ZA --> UI : Updated ZEC available balance
    UI --> ZH : Shows ZEC available for bridging
    ZH -> UI : Initiate bridge reqest
    UI -> MC ++: Request signature
    MC --> UI --: Signature
    UI --> UI : Compose signed ZEC transaction
    UI -> ZA --: Submit signed ZEC transaction + tx fee auth
    ZA -> Z : Submit signed ZEC transaction
    loop Until confirmed depth reached
        ZA -> Z : Poll
        Z --> ZA --: Reply
    end 
end


group Validate
    ZA -> ZCE ++: Submit vetted request for validation
    ZCE -> ZCE : check for\nno replay
    ZCE -> Z ++: Validate: existence, depth
    Z --> ZCE --: Existence, depth
    note left: Each ZavaX warden\nqueries its own\nZebra instance
    ZCE -> ZCE : Write block\nwith ZEC.z\nminting message
end 

group Mint ZEC.z on Avalanche
    loop until timeout
        ZA -> ZCE : Poll for warp message
    end

    opt If approved
        ZCE --> ZA : Warp message to mint ZEC.z
        deactivate ZCE
        ZA -> ZC ++: Relay ZEC.z minting message + gas
        ZC -> ZC : Verify threshold\nsignature, weight
        ZC -> ZC : Mint ZEC.z
        ZC -> CC ++: Send ZEC.z to AVAX wallet address 
    end 
    deactivate ZC
end 

group Refresh balance and account info for the ZEC Owner
    ZA --> UI : Bridging is complete
    UI -> MC ++: Request ZEC.z balance
    MC -> CC : Request ZEC.z balance
    CC --> MC --: ZEC.z available balance
    MC --> UI --: ZEC.z available balance
    ZA -> Z ++: Get ZEC balance
    Z --> ZA --: Updated ZEC balance
    ZA --> UI --: Updated ZEC balance & Results
    UI --> ZH --: Final Results 
end
@enduml
