@startuml

skinparam sequenceMessageAlign right
title Create ZavaX Validator

actor "ZAX Owner" as ZO
entity "Avalanche-cli" as AC
entity "Ledger" as L
entity "Avalanche\nP-Chain" as AP

ZO -> AC++ : Initiate validation\nand set\nZavaX Agent fees 
AC -> L++ : Request signature
L -> ZO : Request approval 
ZO --> L : Approve
L -> L : Sign transaction
L -> AC-- : Signed transaction
AC -> AP++ : Request validation
AP --> AC-- : Response
AC --> ZO-- : Response

@enduml