@startuml

title Maintain ZavaX Wardens and Wallet Control
participant "ZavaX\nAgent" as ZA
entity "Avalanche\nP-Chain" as AP
participant "ZavaX\nConsensus\nEngine" as ZCE
participant "New/Continuing\nWardens" as NV
participant "Current\nWardens" as PV
entity "Zebra" as Z

autonumber
group Preapare for maintenance
    loop
        ZA -> ZA++ : Wait for next\n5 min per 24 hr\ntime slot to become\ncertified Agent
    end
    ZA -> AP++ : New and previously\nabsent ZavaX validators?
    AP --> ZA : List of new ZavaX validators
    ZA -> AP : Expiring ZavaX validators?
    AP --> ZA-- : List of expiring ZavaX validators
end
group Prepare new bridge wallet 
    ZA -> ZCE++ : Make wardens change request\n(certified Agents only)
    ZCE -> ZCE : Verify ZavaX Agent\ncertification & change request
    ZCE -[#red]> ZCE : <color:red>Write block: <b>Status: Down\n'<color:red>ZavaX bridge down for maintenance'
    ZCE -> NV++ : Create new distributed private key
    NV -> NV : Create new BLS keys,\n1 key per 0.1% stake
    NV --> ZCE-- : Each submit public key part
    ZCE -> ZCE : Check for warden quorum
    ZCE -> ZCE : Aggregate public key\n& wallet address, and\nwrite to a block
    ZCE --> ZA --: New wallet address
end 
group Migrate from current to new bridge wallet
    ZA -> Z ++: Request current wallet balance
    Z --> ZA --: Current wallet balance
    ZA -> ZCE ++: Unsigned xfer transaction\nfrom current to new wallet\n(consolidate UTXOs)\n(certified Agents only)
    ZCE -> ZCE : Verify xfer
    ZCE -> PV++ : Gather signatures
    PV --> ZCE-- : Each submit signatures
    ZCE -> ZCE : Write signatures to a block
    ZCE --> ZA--: Signatures ready
    ZA -> ZA : Combine signatures
    ZA -> ZA : sign xfer
    ZA -> Z++ : Submit signed xfer to new wallet
    loop until confirmed depth reached
        ZA -> Z: Poll for block depth
        Z --> ZA--: Return depth
    end 
end 
group Finish bridge maintenance
    ZA -> ZCE++ : Wallet migration successful?\n(any Agent)
    ZCE -> PV++ : Verify
    PV --> ZCE--: Accepted/rejected
    ZCE -> ZCE: Queue bridge toll fees for\nexpiring wardens\nand certified ZavaX Agent
    ZCE -> ZCE: Update wallet address, clean up,\nand prep for next day\n(certified Agent timing list, etc.)
    ZCE -> ZCE: Write block with results
    ZCE -[#green]> ZCE: <color:green>Write block: <b>Status: Up\n<color:green>'ZavaX bridge functioning normally.'
    ZCE --> ZA --: Results
end 
@enduml
