@startuml

skinparam sequenceMessageAlign right
title ZavaX Validator Expires

participant "ZavaX\nConsensus\nEngine" as ZCE
entity "Avalanche\nP-Chain" as AP

autonumber
loop
    ZCE -> ZCE ++: Wait for expiration
    ZCE -> ZCE : Calulate fees earned & penalties
    ZCE -> AP : Send validation reward \nto expiring validator
    note right : Rivision possible to\nsend accumulated fees earned to\nC-Chain and/or Zcash wallet 
end


@enduml