@startuml
left to right direction
title ZavaX Bridge Deployment - Network
Node ":Web Server" as WS {

    [ZavaX\nBridge UI]
}

Cloud Internet as I

Node "<b>:Zavax Node 1" as ZN1
Node "<b>:Zavax Node 2" as ZN2
Node "<b>:Zavax Node 3" as ZN3
Node "<b>:Zavax Node 4" as ZN4
Node "<b>:Zavax Node 5" as ZN5
Node "<b>:Zavax Node 6" as ZN6
Node "<b><i>... :Zavax Node N-1" as ZN7
Node "<b><i>:Zavax Node N" as ZNX

ZN1 -- I : TLS
ZN2 -- I : TLS
ZN3 -- I : TLS
ZN4 -- I : TLS
ZN5 -- I : TLS
ZN6 -- I : TLS
ZN7 -- I : TLS
ZNX -- I : TLS
WS -- I : TLS
@enduml