@startuml
title ZavaX Bridge Deployment - One Node and Web Server

Cloud Internet as I

Node ":Web Server" as WS {

    [ZavaX\nBridge UI]
}

Node ":Zavax Node" as ZN {
    Package "ZavaX" as ZX {
        [ZavaX\nAgent] as ZA 
    }
'    [ZEC.z\nContract] as ZC
    Package "AvalancheGo" as AG {
        Package "Subnets" as SP {
            [ZavaX\nConsensus\nEngine] as ZCE
        }
        Package "Primary Network" as PN {
            entity "Avalanche\nC-Chain" as CC
            entity "Avalanche\nP-Chain" as AP
            entity "Avalanche\nX-Chain" as XC
        }
    }
    Package "Zebra" as Z {
        entity "Zcash\nChain" as ZCC
    }
}

ZX -- I : TLS
WS -- I : TLS
ZA -- ZCE : RPC
ZA -- ZCC : RPC
ZA -- PN : RPC


@enduml